default:
  image: node:lts
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # - if: $CI_COMMIT_TAG
    # - if: $CI_COMMIT_REF_PROTECTED

stages:
  - test
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - npm run build

#lintテスト
lint:
  stage: test
  script:
    - npm run lint

.deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $CI_JOB_JWT_V2
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
  cache: {}
  script:
    - aws s3 sync dist s3://${AWS_BUCKET}
    - aws s3 cp dist/index.html s3://${AWS_BUCKET}/index.html --cache-control 60
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
